spring:
  datasource:
    url: jdbc:mysql://springsecurity.cccrh82skk1r.us-east-2.rds.amazonaws.com/eazybank
    username: admin
    password: mysqlspringsecurity
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
